### PR TITLE
MC Update

### PR DESCRIPTION
**Pull request by jules6077**
The MuonCVXDDigitizer.cc script has been edited to optimize the 4-bit ToT-charge.

### CODE REVIEW

**Comment by jules6077** [comment]
@spagangriso

**Comment by spagangriso** [comment]
Thank you @jules6077 ! As Angira mentioned, can you look at the "diff" here and restore the same debug level in the messages that we had before? If you have little time no worries, just let me know and I'll take care of it.

Tagging also @madbaron; such that when this is ready (pretty soon) he's aware it gets into master.

**Comment by jules6077** [comment]
Yes @spagangriso. I'll reset the original DEBUG levels right now.

**Comment by spagangriso** [comment]
Perfect, thank you @jules6077 !!

**Comment by jules6077** [comment]
You're welcome! Let me know if you need me to do anything else

**Pull request merged**
